name: browse-scaler Node.js CI

on:
  push:
    branch:
      - 'master'
    paths:
      - 'browse-scaler/**'
  pull_request:
    paths:
      - 'browse-scaler/**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CMR_ENVIRONMENT: 'ci'
      CMR_ROOT: 'cmr.ci-test.earthdata.nasa.gov'
      CMR_ECHO_TOKEN: 'ci-test-token'

    defaults:
      run:
        working-directory: browse-scaler/src
    
    paths-ignore:
     - '__mocks__/**'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 7

    - run: npm install

    - run: npm run ci-test

    - uses: codecov/codecov-action@v2
      with:
        name: browse-scaler-coverage
