# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: graph-db Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'graph-db/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'graph-db/**'
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: graph-db

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      # Label used to access the service container
      gremlin-server:
        # Docker Hub image
        image: tinkerpop/gremlin-server
        #
        ports:
          # Opens tcp port 8182 on the host and service container
          - 8182:8182
          
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
